package Swing;

import javax.swing.JOptionPane;

public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMenuPrincipal = new javax.swing.JLabel();
        lblEmpleados = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblProveedores = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        lblImagenPrincipal = new javax.swing.JLabel();
        btnIngresarEmpleados = new javax.swing.JButton();
        btnIngresarProductos = new javax.swing.JButton();
        btnIngresarVentas = new javax.swing.JButton();
        btnIngresarClientes = new javax.swing.JButton();
        btnIngresarProveedores = new javax.swing.JButton();
        lblPago = new javax.swing.JLabel();
        btnIngresarPago = new javax.swing.JButton();
        lblVentas = new javax.swing.JLabel();
        btnIngresarCategorias = new javax.swing.JButton();
        lblRol = new javax.swing.JLabel();
        btnIngresarRol = new javax.swing.JButton();
        lblServicio = new javax.swing.JLabel();
        btnIngresarServicio = new javax.swing.JButton();
        lblSucursal = new javax.swing.JLabel();
        btnIngresarSucursal = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblPuesto1 = new javax.swing.JLabel();
        btnIngresarListaVentas1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuOpcionSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Villa Pet");

        lblMenuPrincipal.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuPrincipal.setText("MENÚ PRINCIPAL");

        lblEmpleados.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleados.setText("Empleados");
        lblEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblClientes.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setText("Clientes");
        lblClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblProveedores.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblProveedores.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedores.setText("Proveedores");
        lblProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblPuesto.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblPuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblPuesto.setText("Categoria");
        lblPuesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPuesto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblProductos.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblProductos.setText("Productos");
        lblProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblImagenPrincipal.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblImagenPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblImagenPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/principal.png"))); // NOI18N

        btnIngresarEmpleados.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarEmpleados.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarEmpleados.setText("INGRESAR EMPLEADOS");
        btnIngresarEmpleados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEmpleadosActionPerformed(evt);
            }
        });

        btnIngresarProductos.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarProductos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarProductos.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarProductos.setText("INGRESAR PRODUCTOS");
        btnIngresarProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProductosActionPerformed(evt);
            }
        });

        btnIngresarVentas.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarVentas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarVentas.setText("INGRESAR VENTAS");
        btnIngresarVentas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarVentasActionPerformed(evt);
            }
        });

        btnIngresarClientes.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarClientes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarClientes.setText("INGRESAR CLIENTES");
        btnIngresarClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarClientesActionPerformed(evt);
            }
        });

        btnIngresarProveedores.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarProveedores.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarProveedores.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarProveedores.setText("INGRESAR PROVEEDORES");
        btnIngresarProveedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProveedoresActionPerformed(evt);
            }
        });

        lblPago.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblPago.setForeground(new java.awt.Color(255, 255, 255));
        lblPago.setText("Pagos");
        lblPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPago.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnIngresarPago.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarPago.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarPago.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarPago.setText("INGRESAR PAGOS");
        btnIngresarPago.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPagoActionPerformed(evt);
            }
        });

        lblVentas.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(255, 255, 255));
        lblVentas.setText("Ventas");
        lblVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnIngresarCategorias.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarCategorias.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarCategorias.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarCategorias.setText("INGRESAR CATEGORIAS");
        btnIngresarCategorias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCategoriasActionPerformed(evt);
            }
        });

        lblRol.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblRol.setForeground(new java.awt.Color(255, 255, 255));
        lblRol.setText("Roles");
        lblRol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnIngresarRol.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarRol.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarRol.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarRol.setText("INGRESAR ROLES");
        btnIngresarRol.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarRol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarRolActionPerformed(evt);
            }
        });

        lblServicio.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblServicio.setForeground(new java.awt.Color(255, 255, 255));
        lblServicio.setText("Servicios");
        lblServicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblServicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnIngresarServicio.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarServicio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarServicio.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarServicio.setText("INGRESAR SERVICIOS");
        btnIngresarServicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarServicioActionPerformed(evt);
            }
        });

        lblSucursal.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblSucursal.setForeground(new java.awt.Color(255, 255, 255));
        lblSucursal.setText("Sucursal");
        lblSucursal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSucursal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnIngresarSucursal.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarSucursal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarSucursal.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarSucursal.setText("INGRESAR SUCURSAL");
        btnIngresarSucursal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarSucursalActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/cerrar sesion peq.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lblPuesto1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lblPuesto1.setForeground(new java.awt.Color(255, 255, 255));
        lblPuesto1.setText("Lista de Ventas");
        lblPuesto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPuesto1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnIngresarListaVentas1.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarListaVentas1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnIngresarListaVentas1.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarListaVentas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/actualizar.png"))); // NOI18N
        btnIngresarListaVentas1.setText("INGRESAR LISTA VENTAS");
        btnIngresarListaVentas1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarListaVentas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarListaVentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarListaVentas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerrarSesion)
                        .addGap(268, 268, 268)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMenuPrincipal)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblImagenPrincipal)))
                        .addGap(263, 263, 263)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmpleados)
                            .addComponent(btnIngresarEmpleados)
                            .addComponent(btnIngresarClientes)
                            .addComponent(btnIngresarProductos)
                            .addComponent(btnIngresarVentas)
                            .addComponent(btnIngresarPago)
                            .addComponent(lblPago)
                            .addComponent(lblProductos)
                            .addComponent(lblClientes)
                            .addComponent(lblVentas))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresarListaVentas1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPuesto1)
                                .addGap(47, 47, 47)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresarProveedores)
                            .addComponent(lblProveedores)
                            .addComponent(btnIngresarCategorias)
                            .addComponent(btnIngresarRol)
                            .addComponent(btnIngresarSucursal)
                            .addComponent(btnIngresarServicio)
                            .addComponent(lblServicio)
                            .addComponent(lblPuesto)
                            .addComponent(lblRol)
                            .addComponent(lblSucursal))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMenuPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImagenPrincipal))
                    .addComponent(btnCerrarSesion))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblProveedores)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIngresarProveedores))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEmpleados)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIngresarEmpleados)))
                                .addGap(24, 24, 24)
                                .addComponent(lblPuesto))
                            .addComponent(lblClientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIngresarClientes)
                                    .addComponent(btnIngresarCategorias))
                                .addGap(24, 24, 24)
                                .addComponent(lblRol))
                            .addComponent(lblProductos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIngresarRol)
                                    .addComponent(btnIngresarProductos))
                                .addGap(24, 24, 24)
                                .addComponent(lblServicio))
                            .addComponent(lblPago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresarServicio)
                            .addComponent(btnIngresarPago))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSucursal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIngresarVentas)
                                    .addComponent(btnIngresarSucursal)))
                            .addComponent(lblVentas))
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPuesto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIngresarListaVentas1)
                        .addGap(90, 90, 90))))
        );

        menuOpciones.setText("Opciones");

        menuOpcionSalir.setText("Salir");
        menuOpcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(menuOpcionSalir);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuOpcionSalirActionPerformed

    private void btnIngresarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEmpleadosActionPerformed
        // TODO add your handling code here:
        JFEmpleado empleado = new JFEmpleado();
        empleado.setVisible(true);
        empleado.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarEmpleadosActionPerformed

    private void btnIngresarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProductosActionPerformed
        // TODO add your handling code here:
        JFProducto producto = new JFProducto();
        producto.setVisible(true);
        producto.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarProductosActionPerformed

    private void btnIngresarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarVentasActionPerformed
        // TODO add your handling code here:
        JFVenta venta = new JFVenta();
        venta.setVisible(true);
        venta.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarVentasActionPerformed

    private void btnIngresarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarClientesActionPerformed
        // TODO add your handling code here:
        JFCliente cliente = new JFCliente();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarClientesActionPerformed

    private void btnIngresarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProveedoresActionPerformed
        // TODO add your handling code here:
        JFProveedor proveedor = new JFProveedor();
        proveedor.setVisible(true);
        proveedor.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarProveedoresActionPerformed

    private void btnIngresarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPagoActionPerformed
        // TODO add your handling code here:
        JFPago pago = new JFPago();
        pago.setVisible(true);
        pago.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarPagoActionPerformed

    private void btnIngresarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCategoriasActionPerformed
        // TODO add your handling code here:
        JFCategoria categoria = new JFCategoria();
        categoria.setVisible(true);
        categoria.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarCategoriasActionPerformed

    private void btnIngresarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarRolActionPerformed
        // TODO add your handling code here:
        JFRol rol = new JFRol();
        rol.setVisible(true);
        rol.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarRolActionPerformed

    private void btnIngresarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarServicioActionPerformed
        // TODO add your handling code here:
        JFServicio servicio = new JFServicio();
        servicio.setVisible(true);
        servicio.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarServicioActionPerformed

    private void btnIngresarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarSucursalActionPerformed
        // TODO add your handling code here:
        JFSucursal sucursal = new JFSucursal();
        sucursal.setVisible(true);
        sucursal.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarSucursalActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        JFAcceso acceso = new JFAcceso();

        acceso.setVisible(true);
        
        acceso.setLocationRelativeTo(null);

        dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnIngresarListaVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarListaVentas1ActionPerformed
        // TODO add your handling code here:
        JFVenta_Lista listaVenta = new JFVenta_Lista();
        listaVenta.setVisible(true);
        listaVenta.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarListaVentas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnIngresarCategorias;
    private javax.swing.JButton btnIngresarClientes;
    private javax.swing.JButton btnIngresarEmpleados;
    private javax.swing.JButton btnIngresarListaVentas1;
    private javax.swing.JButton btnIngresarPago;
    private javax.swing.JButton btnIngresarProductos;
    private javax.swing.JButton btnIngresarProveedores;
    private javax.swing.JButton btnIngresarRol;
    private javax.swing.JButton btnIngresarServicio;
    private javax.swing.JButton btnIngresarSucursal;
    private javax.swing.JButton btnIngresarVentas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblImagenPrincipal;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblProveedores;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblPuesto1;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JMenuItem menuOpcionSalir;
    private javax.swing.JMenu menuOpciones;
    // End of variables declaration//GEN-END:variables
}
